### ISSUE TITLE
XGS-ONU-25-20NI

### ISSUE THREAD

**Issue by TKinslayer** [StephanGR/gobox#7] opened 2024-02-16 17:33 UTC
Avant de me lancer, est-ce que le soft est compatible avec le XGS-ONU-25-20NI ? (pour la version 10G) Ou bien c'est propre au LEOX GPON STICK LXT-010S-H ?

Peut-être une question idiote, mais avant de cramer 250 euros si je me plante vraiment ;-)

**Comment by iMord0** [comment] 2024-02-16 21:38
Unfortunately FS uses different commands than LEOX, but you can absolutely copy the values and change the syntax. Be aware that 1Gbps FS module crashes UDM SE (at least in my case), can't tell if 10Gbps version has the same issue. I have confirmed that Lantiq based SFPs (for example 1 Gbps FS) have issues and Realtek (Leox) ones works fine, in your case it is Cortina with which I don't have any experience.
Here you can find some useful info: https://hack-gpon.org/xgs/ont-fs-XGS-ONU-25-20NI/

**Comment by TKinslayer** [comment] 2024-02-17 06:01
Actually, shortly after I posted here, I read someone did use a XGS-ONU-25-20NI and it worked. But he had to set it all up manually. I'm trying to understand how it all works out. When you say "but you can absolutely copy the values and change the syntax" - does it means I can use your software to get the needed values, and then telnet to the ONU and set the values manually by 'changing the syntax' ?

**Comment by iMord0** [comment] 2024-02-17 08:28
for example software output is:
`flash set PON_VENDOR_ID SMBS`
You get the value "SMBS" and use it in corresponding command to your SFP:
`vendor set "SMBS"`
By syntax I mean commands - those are different, but values can be transferred over. 

Yup you would set it up using telnet, the link sent by me before can help you with needed commands.

**Comment by TKinslayer** [comment] 2024-03-17 13:11
Hi, 
   
I've been over it for a month (well, not fully of course), and I see the logic. Unfortunately, I do have a hard time finding corresponding "commands" in the provided link (here : https://hack-gpon.org/xgs/ont-fs-XGS-ONU-25-20NI/ and the list of shell command here : https://hack-gpon.org/xgs/ont-fs-XGS-ONU-25-20NI-cli/).
I have found several commands to be the explicitly equivalents to the ones you gave in the tutorial (I put them both below in contrast below). 

I would need some explanation as to what some of your commands are meant to achieve, so I can find similarities with what you mention in your tutorial. 

———
flash set GPON_PLOAM_PASSWD DEFAULT012
- exeep_w8 "<DEFAULT012>" [And what does DEFAULT012 means exactly - is that the password from Orange ?]
flash set OMCI_TM_OPT 0
- Not found at the moment
flash set OMCI_OLT_MODE 1
- Not found at the moment
flash set GPON_SN XXXXXXXXXXXX
- eqsn set "<value>"
flash set PON_VENDOR_ID SMBS
- vendor set SMBS
flash set HW_HWVER XXXXXXXXXXXX
- eqvid set "<value>"
flash set OMCI_SW_VER1 XXXXXXXXXXXXX
- Not found at the moment
flash set OMCI_SW_VER2 XXXXXXXXXXXXX
- Not found at the moment

**Comment by iMord0** [comment] 2024-03-18 12:23
You do not need GPON_PLOAM_PASSWD - Orange doesn't use it.

For sure you will need:
`flash set GPON_SN SMBS031E9F7D -> eqsn set "SMBS031E9F7D"`
`flash set PON_VENDOR_ID SMBS -> vendor set "SMBS"`

These are only commands I have needed - in my case OLT on the Orange side is Huawei and doesn't need anything else.

You can check OLT status by running this command:
`traffic/pon/show link`
O5 means everything is correct and you can move ONT to WAN and put your credentials in PPPoE section - at least that's how it looks in Poland.
Other statuses require more settings.

With this command you can check vendor of your OLT:
`system/mib/show 131`

Remember - when running show commands you need to plug in the fiber from orange into SFP.

@StephanGR might be able to help with other countries where Orange uses DHCP, not PPPoE

**Comment by Stoufiler** [comment] 2024-04-09 10:28
I've changed my ISP, I'm not using Orange anymore :/

**Comment by Stoufiler** [comment] 2024-08-26 14:38
Closing this issue since no activity from several months

**Closed as completed by Stoufiler** 2024-08-26 14:38 UTC
